version: 2
updates:
  - package-ecosystem: "npm"
    # Files stored in repository root
    directory: "/"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "npm"
    # Files stored in repository server
    directory: "/server"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "npm"
    # Files stored in repository client
    directory: "/client"
    schedule:
      interval: "daily"
